import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = resolve(__dirname, "..");

function readJson(relativePath) {
  const path = resolve(repoRoot, relativePath);
  return JSON.parse(readFileSync(path, "utf8"));
}

function writeJson(relativePath, value) {
  const path = resolve(repoRoot, relativePath);
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function normalize(text) {
  return String(text ?? "").toLowerCase();
}

function parseArgs(argv) {
  const args = argv.slice(2);
  const record = args.includes("--record");
  const styleParts = args.filter((arg) => arg !== "--record");
  return {
    record,
    styleQuery: styleParts.join(" ").trim(),
  };
}

function scoreHop(style, hop) {
  const styleTerms = new Set(
    [
      style.name,
      ...(style.good_hop_traits ?? []),
      ...(style.targets?.aroma ?? []),
      style.targets?.bitterness,
      style.targets?.malt,
    ]
      .flatMap((value) => String(value ?? "").split(/\s+/))
      .map(normalize)
      .filter(Boolean)
  );

  const hopTerms = new Set(
    [hop.name, ...(hop.aroma ?? []), hop.bitterness, ...(hop.best_use ?? [])]
      .flatMap((value) => String(value ?? "").split(/\s+/))
      .map(normalize)
      .filter(Boolean)
  );

  let score = 0;
  for (const term of hopTerms) {
    if (styleTerms.has(term)) score += 2;
  }

  for (const aroma of hop.aroma ?? []) {
    if ((style.targets?.aroma ?? []).map(normalize).includes(normalize(aroma))) {
      score += 3;
    }
    if ((style.good_hop_traits ?? []).map(normalize).includes(normalize(aroma))) {
      score += 2;
    }
  }

  if (
    normalize(style.targets?.bitterness).includes(normalize(hop.bitterness)) ||
    normalize(hop.bitterness).includes(normalize(style.targets?.bitterness))
  ) {
    score += 2;
  }

  if (normalize(style.description).includes("delicate") && normalize(hop.pairing_notes).includes("dominate")) {
    score -= 2;
  }

  return score;
}

function findStyle(styleQuery, styles) {
  const q = normalize(styleQuery);
  if (!q) return null;
  return (
    styles.find((style) => normalize(style.name) === q) ??
    styles.find((style) => normalize(style.name).includes(q) || q.includes(normalize(style.name)))
  );
}

function chooseCombinations(sortedHops) {
  const top = sortedHops.slice(0, 4);
  const combos = [];

  if (top.length >= 2) combos.push([top[0], top[1]]);
  if (top.length >= 3) combos.push([top[0], top[2]]);
  if (top.length >= 4) combos.push([top[1], top[3]]);

  return combos;
}

function explainCombo(style, combo) {
  const names = combo.map((hop) => hop.name).join(" + ");
  const aromas = [...new Set(combo.flatMap((hop) => hop.aroma ?? []))].slice(0, 4).join(", ");
  return `${names} - fits ${style.name} with ${aromas || "balanced hop character"}.`;
}

function updateMemory(record) {
  const tasks = readJson("memory/tasks.json");
  const decisions = readJson("memory/decisions.json");

  tasks.completed.push({
    id: `beer-hop-${Date.now()}`,
    title: record.style.name,
    status: "completed",
    input: record.styleQuery,
    output: record.recommendation,
    notes: "Generated by the local Hermes demo runner.",
  });

  const existingDecision = decisions.decisions.find((item) => item.id === "runner-001");
  const newDecision = {
    id: "runner-001",
    decision: "Use the local Node runner to read refs, rank hops, and optionally record results into memory.",
    reason: "This keeps the demo runnable on an old Intel Mac without extra dependencies.",
  };

  if (existingDecision) {
    Object.assign(existingDecision, newDecision);
  } else {
    decisions.decisions.push(newDecision);
  }

  writeJson("memory/tasks.json", tasks);
  writeJson("memory/decisions.json", decisions);
}

function main() {
  const { record, styleQuery } = parseArgs(process.argv);
  const state = readJson("memory/project-state.json");
  const styles = readJson("refs/beer_styles.json").styles ?? [];
  const hops = readJson("refs/hop_catalog.json").hops ?? [];

  const style =
    findStyle(styleQuery, styles) ??
    styles[0];

  const ranked = [...hops]
    .map((hop) => ({ ...hop, score: scoreHop(style, hop) }))
    .sort((a, b) => b.score - a.score);

  const combos = chooseCombinations(ranked);
  const recommendation = combos[0] ?? [];

  const report = {
    project: state.project,
    mode: state.mode,
    input: styleQuery || style.name,
    style,
    top_hops: ranked.slice(0, 3).map((hop) => ({
      name: hop.name,
      score: hop.score,
      aroma: hop.aroma,
      best_use: hop.best_use,
    })),
    combos: combos.map((combo) => combo.map((hop) => hop.name)),
    recommendation: explainCombo(style, recommendation),
    notes: [
      "This is a lightweight heuristic demo, not a brewing calculator.",
      "It uses local refs and memory only.",
    ],
  };

  if (record) {
    updateMemory({
      styleQuery: styleQuery || style.name,
      style,
      recommendation: report.recommendation,
    });
  }

  console.log(JSON.stringify(report, null, 2));
}

main();
